[package]
name = "tiny_tot_vm"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ttvm"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4"
comfy-table = "7"
colored = "2.0"
tabled = "0.15"
